name: Update Changelog

on:
  workflow_dispatch:   # tu peux aussi ajouter "schedule" ou "push"

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Auto-commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: CHANGELOG.md
          commit_message: "Update CHANGELOG"
          branch: changelog-update   # 👉 branche temporaire pour les changements

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          branch: changelog-update
          base: main
          title: "Update CHANGELOG"
          body: "This PR updates the CHANGELOG automatically."
          labels: automated-pr
          draft: false

      - name: Auto-merge Pull Request
        if: steps.cpr.outputs.pull-request-url != ''
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
          repo-token: ${{ secrets.GITHUB_TOKEN }}
